### ISSUE TITLE
Problem compiling with Arduino 1.6.6 / "core.a" file not found

### ISSUE THREAD

**Issue by chatelao** [sparkfun/PSoC_Arduino_Support#13]
Something in the core-configuration seams to cause problems:

Warning: platform.txt from core 'SparkFun PSoC Development Boards' contains deprecated compiler.path={runtime.ide.path}/hardware/tools/gcc-arm-none-eabi-4.8.3-2014q1/bin/, automatically converted to compiler.path={runtime.tools.arm-none-eabi-gcc.path}/bin/. Consider upgrading this core.

Warning: platform.txt from core 'SparkFun PSoC Development Boards' contains deprecated recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{build.path}/{archive_file}" "{object_file}", automatically converted to recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{archive_file_path}" "{object_file}". Consider upgrading this core.

...

"C:\Users\hp\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-gcc" -Wl,--start-group -o "C:\Users\hp\AppData\Local\Temp\buildc327d20fff43152b5d828eb86f3c098d.tmp/sketch_dec18a.ino.elf" "C:\Users\hp\AppData\Local\Temp\buildc327d20fff43152b5d828eb86f3c098d.tmp\sketch\sketch_dec18a.ino.cpp.o" "C:\Users\hp\Documents\Arduino\hardware\SparkFun\psoc\variants\standard/Uno_blocks.a" "C:\Users\hp\Documents\Arduino\hardware\SparkFun\psoc\variants\standard/CyCompLib.a" "C:\Users\hp\AppData\Local\Temp\buildc327d20fff43152b5d828eb86f3c098d.tmp/core.a"  -mthumb -march=armv7-m -mfix-cortex-m3-ldrd -lm "-Wl,-Map,C:\Users\hp\AppData\Local\Temp\buildc327d20fff43152b5d828eb86f3c098d.tmp/sketch_dec18a.ino.map" "-TC:\Users\hp\Documents\Arduino\hardware\SparkFun/psoc/cores/arduino/cm3gcc.ld" -g "-u _printf_float" ""  -Wl,--gc-sections -Wl,--end-group -lstdc++
arm-none-eabi-gcc: error: C:\Users\hp\AppData\Local\Temp\buildc327d20fff43152b5d828eb86f3c098d.tmp/core.a: No such file or directory 
arm-none-eabi-gcc: error: : No such file or directory

**Comment by mhord** [comment]
I haven't revisited this since 1.6.6 hit; I'll take a look. I know it needs a serious update, so it can work with the boards manager, but for now I'll see if I can at least get it working.

**Comment by chatelao** [comment]
Version 1.6.7 doesn't work either, just the fall-back to 1.6.5-r5 is fine.
If you need the script to setup your environment, feel free to reuse / distribute:

'''
set version=1.6.7
arduino-%version%\arduino_debug --pref "boardsmanager.additional.urls=https://raw.githubusercontent.com/sparkfun/Arduino_Boards/master/IDE_Board_Manager/package_sparkfun_index.json"
arduino-%version%\arduino_debug --install-boards arduino:sam
arduino-%version%\arduino_debug --pref "compiler.warning_level=all" --save-prefs
'''

**Comment by mhord** [comment]
This is fixed; compiles and loads with v1.8.1.
